### ISSUE TITLE
font improvement script has package conflict

### ISSUE THREAD

**Issue by valentt** [satya164/fedy#126] opened 2015-01-25 13:11 UTC
Improving font rendering
Adding rpmfusion-free.repo
rpmfusion-free.repo already configured
rpmfusion-free.repo is currently not available
Adding rpmfusion-nonfree.repo
rpmfusion-nonfree.repo already configured
rpmfusion-nonfree.repo is currently not available
Loaded plugins: langpacks
http://linux.dropbox.com/fedora/21/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
adobe-linux-x86_64                                                                              |  951 B  00:00:00     
fedora/21/x86_64/metalink                                                                       |  24 kB  00:00:00     
google-chrome                                                                                   |  951 B  00:00:00     
pkerling-seafile                                                                                | 3.0 kB  00:00:00     
rpmfusion-free-updates                                                                          | 2.7 kB  00:00:00     
rpmfusion-nonfree-updates                                                                       | 2.7 kB  00:00:00     
Resolving Dependencies
--> Running transaction check
---> Package freetype-freeworld.x86_64 0:2.5.3-3.fc21 will be installed
--> Processing Conflict: freetype-infinality-2.4.12-1.20130514_01.fc18.x86_64 conflicts freetype-freeworld

Packages skipped because of dependency problems:
    freetype-freeworld-2.5.3-3.fc21.x86_64 from rpmfusion-free-updates
Completed, but with errors!

**Comment by satya164** [comment] 2015-02-08 12:55
Duplicate of #125

**Closed by satya164** 2015-02-08 12:55 UTC
