### ISSUE TITLE
Package ozon-repos-21-5.fc21.noarch.rpm is not signed

### ISSUE THREAD

**Issue by Jobava** [satya164/fedy#162] opened 2015-05-17 23:35 UTC
Cannot run "yum update" or "dnf update" because of the error:

    Package ozon-repos-21-5.fc21.noarch.rpm is not signed

**Comment by satya164** [comment] 2015-05-18 12:32
The issue is fixed now. Please try again.

**Closed** 2015-05-18 20:45 UTC

**Comment by LeleDev** [comment] 2015-05-19 10:18
Still getting the same error:

/var/cache/yum/x86_64/21/ozonos/packages/fedy-4.0.0-1.noarch.rpm: Header V4 RSA/SHA1 Signature, ID chiave b8c0fc22: NOKEY
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos


Retrieving GPG key error: [Errno 14] curl#37 - "Couldn't open file /etc/pki/rpm-gpg/RPM-GPG-KEY-ozonos"

**Comment by satya164** [comment] 2015-05-19 10:20
You can try the following,

```
sudo yum erase fedy
sudo yum clean expire-cache
sudo yum install http://goodies.ozon-os.com/repo/21/noarch/ozon-repos-21-5.fc21.noarch.rpm
sudo yum install http://goodies.ozon-os.com/repo/21/noarch/fedy-4.0.0-1.noarch.rpm
```

**Comment by LeleDev** [comment] 2015-05-19 10:29
Solved, thank you!

**Comment by satya164** [comment] 2015-05-19 10:31
Cool :D

**Comment by orlandoaleman** [comment] 2015-05-29 06:58
Fixed here! Thanks
